
import pandas as pd

csv_file_path = 'MICRODADOS_ENEM_2023.csv'
output_parquet_file_path = 'MICRODADOS_ENEM_2023.parquet'

def transformarArquivo():
    df_csv = pd.read_csv(csv_file_path, encoding='latin1', sep=';')
    df_csv.to_parquet(output_parquet_file_path, index=False)

def transformarColunas():
    df_parquet['NU_INSCRICAO'] = df_parquet['NU_INSCRICAO'].astype('int32')
    df_parquet['NU_ANO'] = df_parquet['NU_ANO'].astype('int16')
    df_parquet['TP_FAIXA_ETARIA'] = df_parquet['TP_FAIXA_ETARIA'].astype('int16')
    df_parquet['TP_SEXO'] = df_parquet['TP_SEXO'].astype('category')
    df_parquet['TP_ESTADO_CIVIL'] = df_parquet['TP_ESTADO_CIVIL'].astype('int8')
    df_parquet['TP_COR_RACA'] = df_parquet['TP_COR_RACA'].astype('int8')
    df_parquet['TP_NACIONALIDADE'] = df_parquet['TP_NACIONALIDADE'].astype('int8')
    df_parquet['TP_ST_CONCLUSAO'] = df_parquet['TP_ST_CONCLUSAO'].astype('int8')
    df_parquet['TP_ANO_CONCLUIU'] = df_parquet['TP_ANO_CONCLUIU'].astype('int8')
    df_parquet['TP_ESCOLA'] = df_parquet['TP_ESCOLA'].astype('int8')
    df_parquet['TP_ENSINO'] = df_parquet['TP_ENSINO'].astype('int8')
    df_parquet['IN_TREINEIRO'] = df_parquet['IN_TREINEIRO'].astype('bool')
    df_parquet['CO_MUNICIPIO_ESC'] = df_parquet['CO_MUNICIPIO_ESC'].astype('int32')
    df_parquet['NO_MUNICIPIO_ESC'] = df_parquet['NO_MUNICIPIO_ESC'].astype('category')
    df_parquet['CO_UF_ESC'] = df_parquet['CO_UF_ESC'].astype('int8')
    df_parquet['SG_UF_ESC'] = df_parquet['SG_UF_ESC'].astype('category')
    df_parquet['TP_DEPENDENCIA_ADM_ESC'] = df_parquet['TP_DEPENDENCIA_ADM_ESC'].astype('int8')
    df_parquet['TP_LOCALIZACAO_ESC'] = df_parquet['TP_LOCALIZACAO_ESC'].astype('int8')
    df_parquet['TP_SIT_FUNC_ESC'] = df_parquet['TP_SIT_FUNC_ESC'].astype('int8')
    df_parquet['CO_MUNICIPIO_PROVA'] = df_parquet['CO_MUNICIPIO_PROVA'].astype('int32')
    df_parquet['NO_MUNICIPIO_PROVA'] = df_parquet['NO_MUNICIPIO_PROVA'].astype('category')
    df_parquet['CO_UF_PROVA'] = df_parquet['CO_UF_PROVA'].astype('int8')
    df_parquet['SG_UF_PROVA'] = df_parquet['SG_UF_PROVA'].astype('category')
    df_parquet['TP_PRESENCA_CN'] = df_parquet['TP_PRESENCA_CN'].astype('int8')
    df_parquet['TP_PRESENCA_CH'] = df_parquet['TP_PRESENCA_CH'].astype('int8')
    df_parquet['TP_PRESENCA_LC'] = df_parquet['TP_PRESENCA_LC'].astype('int8')
    df_parquet['TP_PRESENCA_MT'] = df_parquet['TP_PRESENCA_MT'].astype('int8')
    df_parquet['CO_PROVA_CN'] = df_parquet['CO_PROVA_CN'].astype('int8')
    df_parquet['CO_PROVA_CH'] = df_parquet['CO_PROVA_CH'].astype('int8')
    df_parquet['CO_PROVA_LC'] = df_parquet['CO_PROVA_LC'].astype('int8')
    df_parquet['CO_PROVA_MT'] = df_parquet['CO_PROVA_MT'].astype('int8')
    df_parquet['NU_NOTA_CN'] = df_parquet['NU_NOTA_CN'].astype('float32')
    df_parquet['NU_NOTA_CH'] = df_parquet['NU_NOTA_CH'].astype('float32')
    df_parquet['NU_NOTA_LC'] = df_parquet['NU_NOTA_LC'].astype('float32')
    df_parquet['NU_NOTA_MT'] = df_parquet['NU_NOTA_MT'].astype('float32')
    df_parquet['TX_RESPOSTAS_CN'] = df_parquet['TX_RESPOSTAS_CN'].astype('category')
    df_parquet['TX_RESPOSTAS_CH'] = df_parquet['TX_RESPOSTAS_CH'].astype('category')
    df_parquet['TX_RESPOSTAS_LC'] = df_parquet['TX_RESPOSTAS_LC'].astype('category')
    df_parquet['TX_RESPOSTAS_MT'] = df_parquet['TX_RESPOSTAS_MT'].astype('category')
    df_parquet['TP_LINGUA'] = df_parquet['TP_LINGUA'].astype('int8')
    df_parquet['TX_GABARITO_CN'] = df_parquet['TX_GABARITO_CN'].astype('category')
    df_parquet['TX_GABARITO_CH'] = df_parquet['TX_GABARITO_CH'].astype('category')
    df_parquet['TX_GABARITO_LC'] = df_parquet['TX_GABARITO_LC'].astype('category')
    df_parquet['TX_GABARITO_MT'] = df_parquet['TX_GABARITO_MT'].astype('category')
    df_parquet['TP_STATUS_REDACAO'] = df_parquet['TP_STATUS_REDACAO'].astype('int8')
    df_parquet['NU_NOTA_COMP1'] = df_parquet['NU_NOTA_COMP1'].astype('int8')
    df_parquet['NU_NOTA_COMP2'] = df_parquet['NU_NOTA_COMP2'].astype('int8')
    df_parquet['NU_NOTA_COMP3'] = df_parquet['NU_NOTA_COMP3'].astype('int8')
    df_parquet['NU_NOTA_COMP4'] = df_parquet['NU_NOTA_COMP4'].astype('int8')
    df_parquet['NU_NOTA_COMP5'] = df_parquet['NU_NOTA_COMP5'].astype('int8')
    df_parquet['NU_NOTA_REDACAO'] = df_parquet['NU_NOTA_REDACAO'].astype('int8')
    df_parquet['Q001'] = df_parquet['Q001'].astype('category')
    df_parquet['Q002'] = df_parquet['Q002'].astype('category')
    df_parquet['Q003'] = df_parquet['Q003'].astype('category')
    df_parquet['Q004'] = df_parquet['Q004'].astype('category')
    df_parquet['Q005'] = df_parquet['Q005'].astype('int8')
    df_parquet['Q006'] = df_parquet['Q004'].astype('category')
    df_parquet['Q007'] = df_parquet['Q004'].astype('category')
    df_parquet['Q008'] = df_parquet['Q004'].astype('category')
    df_parquet['Q009'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0010'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0011'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0012'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0013'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0014'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0015'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0016'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0017'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0018'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0019'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0020'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0021'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0022'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0023'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0024'] = df_parquet['Q004'].astype('category')
    df_parquet['Q0025'] = df_parquet['Q004'].astype('category')

def arredondarNotas():
    df_excel_csv['NU_NOTA_CN'] = df_excel_csv['NU_NOTA_CN'].round(0)
    df_excel_csv['NU_NOTA_CH'] = df_excel_csv['NU_NOTA_CH'].round(0)
    df_excel_csv['NU_NOTA_LC'] = df_excel_csv['NU_NOTA_LC'].round(0)
    df_excel_csv['NU_NOTA_MT'] = df_excel_csv['NU_NOTA_MT'].round(0)


def validarDados():
    

df_parquet = pd.read_parquet('MICRODADOS_ENEM_2023.parquet')


